#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available. Otherwise it will execute while your application is stopped
# before the deploy step. This script gets executed directly, so it
# could be python, php, ruby, etc.
if [ ! -f $OPENSHIFT_DATA_DIR/config/settings.inc.php ]; then
    mkdir $OPENSHIFT_DATA_DIR/config
    touch $OPENSHIFT_DATA_DIR/config/settings.inc.php
fi
ln -sf $OPENSHIFT_DATA_DIR/config/settings.inc.php $OPENSHIFT_REPO_DIR/php/config/settings.inc.php
